spring:
  datasource:
    name: test  #\u6570\u636E\u5E93\u540D
    url: jdbc:mysql://localhost:3306/sl_cms #url
    username: root  #\u7528\u6237\u540D
    password: 123456  #\u5BC6\u7801
    driver-class-name: com.mysql.jdbc.Driver  #\u6570\u636E\u5E93\u94FE\u63A5\u9A71\u52A8
  redis:
    pool:
      host: 127.0.0.1 #连接地址
      port: 6379  #端口号
      config:
        maxTotal: 100
        maxIdle: 10
        maxWaitMillis: 100000 #最大等待时间

server:
   port: 8088

#mybatis:
#    mapper-locations: classpath:mapper/*.xml  #\u914D\u7F6E\u6620\u5C04\u6587\u4EF6
#    type-aliases-package: com.example.test.bean #\u914D\u7F6E\u5B9E\u4F53\u7C7B

